//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.PXEngineSvc
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PXInput.E_GLIDE_PATH", Namespace="http://schemas.datacontract.org/2004/07/PXEngine.Model")]
    public enum PXInputE_GLIDE_PATH : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIFE_TIME = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RETIREMENT = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioData", Namespace="http://schemas.datacontract.org/2004/07/PXEngine.Model")]
    public partial class PortfolioData : object
    {
        
        private TRS.IT.SI.Services.PXEngineSvc.VersionInfo[] VersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TRS.IT.SI.Services.PXEngineSvc.VersionInfo[] Versions
        {
            get
            {
                return this.VersionsField;
            }
            set
            {
                this.VersionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionInfo", Namespace="http://schemas.datacontract.org/2004/07/PXEngine.Model")]
    public partial class VersionInfo : object
    {
        
        private System.Nullable<System.DateTime> EndDtField;
        
        private int IDField;
        
        private TRS.IT.SI.Services.PXEngineSvc.PortfolioInfo[] PorfoliosField;
        
        private System.DateTime StartDtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDt
        {
            get
            {
                return this.EndDtField;
            }
            set
            {
                this.EndDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TRS.IT.SI.Services.PXEngineSvc.PortfolioInfo[] Porfolios
        {
            get
            {
                return this.PorfoliosField;
            }
            set
            {
                this.PorfoliosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDt
        {
            get
            {
                return this.StartDtField;
            }
            set
            {
                this.StartDtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioInfo", Namespace="http://schemas.datacontract.org/2004/07/PXEngine.Model")]
    public partial class PortfolioInfo : object
    {
        
        private TRS.IT.SI.Services.PXEngineSvc.FundInfo[] FundsField;
        
        private int IDField;
        
        private int YTR_AggressiveField;
        
        private int YTR_ConservativeField;
        
        private int YTR_ModerateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TRS.IT.SI.Services.PXEngineSvc.FundInfo[] Funds
        {
            get
            {
                return this.FundsField;
            }
            set
            {
                this.FundsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YTR_Aggressive
        {
            get
            {
                return this.YTR_AggressiveField;
            }
            set
            {
                this.YTR_AggressiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YTR_Conservative
        {
            get
            {
                return this.YTR_ConservativeField;
            }
            set
            {
                this.YTR_ConservativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YTR_Moderate
        {
            get
            {
                return this.YTR_ModerateField;
            }
            set
            {
                this.YTR_ModerateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundInfo", Namespace="http://schemas.datacontract.org/2004/07/PXEngine.Model")]
    public partial class FundInfo : object
    {
        
        private string AssetNameField;
        
        private int DIA_AssetClassIDField;
        
        private string FundDescField;
        
        private int FundIDField;
        
        private string FundNameField;
        
        private int FundStyleCodeField;
        
        private string GroupNameField;
        
        private int PercentageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetName
        {
            get
            {
                return this.AssetNameField;
            }
            set
            {
                this.AssetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DIA_AssetClassID
        {
            get
            {
                return this.DIA_AssetClassIDField;
            }
            set
            {
                this.DIA_AssetClassIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FundDesc
        {
            get
            {
                return this.FundDescField;
            }
            set
            {
                this.FundDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FundID
        {
            get
            {
                return this.FundIDField;
            }
            set
            {
                this.FundIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FundName
        {
            get
            {
                return this.FundNameField;
            }
            set
            {
                this.FundNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FundStyleCode
        {
            get
            {
                return this.FundStyleCodeField;
            }
            set
            {
                this.FundStyleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Percentage
        {
            get
            {
                return this.PercentageField;
            }
            set
            {
                this.PercentageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessRuleFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.PX.Model")]
    public partial class BusinessRuleFault : object
    {
        
        private int CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.FMRS.Model")]
    public partial class FundFault : object
    {
        
        private int CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transamerica.com", ConfigurationName="TRS.IT.SI.Services.PXEngineSvc.IPXEngine")]
    public interface IPXEngine
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfo", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.BusinessRuleFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoBusinessRuleFaultFault", Name="BusinessRuleFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.PX.Model")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.FundFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoFundFaultFault", Name="FundFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.FMRS.Model")]
        TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfo(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfo", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoResponse")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrent", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.BusinessRuleFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrentBusinessRuleFaultFault", Name="BusinessRuleFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.PX.Model")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.FundFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrentFundFaultFault", Name="FundFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.FMRS.Model")]
        TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfoCurrent(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrent", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoCurrentResponse")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoCurrentAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFunds", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFundsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.BusinessRuleFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFundsBusinessRuleFaultFault" +
            "", Name="BusinessRuleFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.PX.Model")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRS.IT.SI.Services.PXEngineSvc.FundFault), Action="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFundsFundFaultFault", Name="FundFault", Namespace="http://schemas.datacontract.org/2004/07/TRS.IT.Services.Engines.FMRS.Model")]
        TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfoWithFunds(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath, string fundsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFunds", ReplyAction="http://transamerica.com/IPXEngine/GetPortfolioInfoWithFundsResponse")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoWithFundsAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath, string fundsXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPXEngineChannel : TRS.IT.SI.Services.PXEngineSvc.IPXEngine, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PXEngineClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.PXEngineSvc.IPXEngine>, TRS.IT.SI.Services.PXEngineSvc.IPXEngine
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PXEngineClient(EndpointConfiguration endpointConfiguration) : 
                base(PXEngineClient.GetBindingForEndpoint(endpointConfiguration), PXEngineClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PXEngineClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PXEngineClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PXEngineClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PXEngineClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PXEngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfo(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath)
        {
            return base.Channel.GetPortfolioInfo(contractID, subID, glidePath);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath)
        {
            return base.Channel.GetPortfolioInfoAsync(contractID, subID, glidePath);
        }
        
        public TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfoCurrent(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath)
        {
            return base.Channel.GetPortfolioInfoCurrent(contractID, subID, glidePath);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoCurrentAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath)
        {
            return base.Channel.GetPortfolioInfoCurrentAsync(contractID, subID, glidePath);
        }
        
        public TRS.IT.SI.Services.PXEngineSvc.PortfolioData GetPortfolioInfoWithFunds(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath, string fundsXML)
        {
            return base.Channel.GetPortfolioInfoWithFunds(contractID, subID, glidePath, fundsXML);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.PXEngineSvc.PortfolioData> GetPortfolioInfoWithFundsAsync(string contractID, string subID, TRS.IT.SI.Services.PXEngineSvc.PXInputE_GLIDE_PATH glidePath, string fundsXML)
        {
            return base.Channel.GetPortfolioInfoWithFundsAsync(contractID, subID, glidePath, fundsXML);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPXEngine_IPXEngine))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPXEngine_IPXEngine1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPXEngine))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPXEngine_IPXEngine))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://ip-0a2e65a8.us.aegon.com/ServicesEngine/PX/PXEngine.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPXEngine_IPXEngine1))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com/ServicesEngine/PX/PXEngine.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPXEngine))
            {
                return new System.ServiceModel.EndpointAddress("http://trs-services-tst.us.aegon.com/ServicesEngine/PX/PXEngine.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IPXEngine_IPXEngine,
            
            NetTcpBinding_IPXEngine_IPXEngine1,
            
            BasicHttpBinding_IPXEngine,
        }
    }
}
