//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsReports
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/", ConfigurationName="TRS.IT.SI.Services.wsReports.ReportsBAImplPortType")]
    public interface ReportsBAImplPortType
    {
        
        // CODEGEN: Generating message contract since element name caseNo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getFundListResponse getFundList(TRS.IT.SI.Services.wsReports.getFundList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getFundListResponse> getFundListAsync(TRS.IT.SI.Services.wsReports.getFundList request);
        
        // CODEGEN: Generating message contract since element name caseNo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getDistributionTypesResponse getDistributionTypes(TRS.IT.SI.Services.wsReports.getDistributionTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDistributionTypesResponse> getDistributionTypesAsync(TRS.IT.SI.Services.wsReports.getDistributionTypes request);
        
        // CODEGEN: Generating message contract since element name caseNo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse getStatementPeriodEndData(TRS.IT.SI.Services.wsReports.getStatementPeriodEndData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse> getStatementPeriodEndDataAsync(TRS.IT.SI.Services.wsReports.getStatementPeriodEndData request);
        
        // CODEGEN: Generating message contract since element name reportInfo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getPlanReportDataResponse getPlanReportData(TRS.IT.SI.Services.wsReports.getPlanReportData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportDataResponse> getPlanReportDataAsync(TRS.IT.SI.Services.wsReports.getPlanReportData request);
        
        // CODEGEN: Generating message contract since element name reportRequest from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.generateReportResponse generateReport(TRS.IT.SI.Services.wsReports.generateReport request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.generateReportResponse> generateReportAsync(TRS.IT.SI.Services.wsReports.generateReport request);
        
        // CODEGEN: Generating message contract since element name reportInfo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getDrillDownDataResponse getDrillDownData(TRS.IT.SI.Services.wsReports.getDrillDownData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDrillDownDataResponse> getDrillDownDataAsync(TRS.IT.SI.Services.wsReports.getDrillDownData request);
        
        // CODEGEN: Generating message contract since element name reportInfo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse getPlanReportAsync(TRS.IT.SI.Services.wsReports.getPlanReportAsync request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse> getPlanReportAsyncAsync(TRS.IT.SI.Services.wsReports.getPlanReportAsync request);
        
        // CODEGEN: Generating message contract since element name reportInfo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getPlanReportResponse getPlanReport(TRS.IT.SI.Services.wsReports.getPlanReport request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportResponse> getPlanReportAsync(TRS.IT.SI.Services.wsReports.getPlanReport request);
        
        // CODEGEN: Generating message contract since element name caseNo from namespace http://reports.businessactivity.webservices.psd.trs.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TRS.IT.SI.Services.wsReports.getSourceListResponse getSourceList(TRS.IT.SI.Services.wsReports.getSourceList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getSourceListResponse> getSourceListAsync(TRS.IT.SI.Services.wsReports.getSourceList request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFundList
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFundList", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getFundListBody Body;
        
        public getFundList()
        {
        }
        
        public getFundList(TRS.IT.SI.Services.wsReports.getFundListBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getFundListBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caseNo;
        
        public getFundListBody()
        {
        }
        
        public getFundListBody(string caseNo)
        {
            this.caseNo = caseNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFundListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFundListResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getFundListResponseBody Body;
        
        public getFundListResponse()
        {
        }
        
        public getFundListResponse(TRS.IT.SI.Services.wsReports.getFundListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getFundListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getFundListResponseBody()
        {
        }
        
        public getFundListResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDistributionTypes
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDistributionTypes", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getDistributionTypesBody Body;
        
        public getDistributionTypes()
        {
        }
        
        public getDistributionTypes(TRS.IT.SI.Services.wsReports.getDistributionTypesBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getDistributionTypesBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caseNo;
        
        public getDistributionTypesBody()
        {
        }
        
        public getDistributionTypesBody(string caseNo)
        {
            this.caseNo = caseNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDistributionTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDistributionTypesResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getDistributionTypesResponseBody Body;
        
        public getDistributionTypesResponse()
        {
        }
        
        public getDistributionTypesResponse(TRS.IT.SI.Services.wsReports.getDistributionTypesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getDistributionTypesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDistributionTypesResponseBody()
        {
        }
        
        public getDistributionTypesResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatementPeriodEndData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStatementPeriodEndData", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataBody Body;
        
        public getStatementPeriodEndData()
        {
        }
        
        public getStatementPeriodEndData(TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getStatementPeriodEndDataBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caseNo;
        
        public getStatementPeriodEndDataBody()
        {
        }
        
        public getStatementPeriodEndDataBody(string caseNo)
        {
            this.caseNo = caseNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatementPeriodEndDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStatementPeriodEndDataResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponseBody Body;
        
        public getStatementPeriodEndDataResponse()
        {
        }
        
        public getStatementPeriodEndDataResponse(TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getStatementPeriodEndDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getStatementPeriodEndDataResponseBody()
        {
        }
        
        public getStatementPeriodEndDataResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReportData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReportData", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportDataBody Body;
        
        public getPlanReportData()
        {
        }
        
        public getPlanReportData(TRS.IT.SI.Services.wsReports.getPlanReportDataBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportDataBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reportInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string returnFormat;
        
        public getPlanReportDataBody()
        {
        }
        
        public getPlanReportDataBody(string reportInfo, string returnFormat)
        {
            this.reportInfo = reportInfo;
            this.returnFormat = returnFormat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReportDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReportDataResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportDataResponseBody Body;
        
        public getPlanReportDataResponse()
        {
        }
        
        public getPlanReportDataResponse(TRS.IT.SI.Services.wsReports.getPlanReportDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getPlanReportDataResponseBody()
        {
        }
        
        public getPlanReportDataResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateReport
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateReport", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.generateReportBody Body;
        
        public generateReport()
        {
        }
        
        public generateReport(TRS.IT.SI.Services.wsReports.generateReportBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class generateReportBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reportRequest;
        
        public generateReportBody()
        {
        }
        
        public generateReportBody(string reportRequest)
        {
            this.reportRequest = reportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateReportResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.generateReportResponseBody Body;
        
        public generateReportResponse()
        {
        }
        
        public generateReportResponse(TRS.IT.SI.Services.wsReports.generateReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class generateReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generateReportResponseBody()
        {
        }
        
        public generateReportResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDrillDownData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDrillDownData", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getDrillDownDataBody Body;
        
        public getDrillDownData()
        {
        }
        
        public getDrillDownData(TRS.IT.SI.Services.wsReports.getDrillDownDataBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getDrillDownDataBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reportInfo;
        
        public getDrillDownDataBody()
        {
        }
        
        public getDrillDownDataBody(string reportInfo)
        {
            this.reportInfo = reportInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDrillDownDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDrillDownDataResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getDrillDownDataResponseBody Body;
        
        public getDrillDownDataResponse()
        {
        }
        
        public getDrillDownDataResponse(TRS.IT.SI.Services.wsReports.getDrillDownDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getDrillDownDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDrillDownDataResponseBody()
        {
        }
        
        public getDrillDownDataResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReportAsync
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReportAsync", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportAsyncBody Body;
        
        public getPlanReportAsync()
        {
        }
        
        public getPlanReportAsync(TRS.IT.SI.Services.wsReports.getPlanReportAsyncBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportAsyncBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reportInfo;
        
        public getPlanReportAsyncBody()
        {
        }
        
        public getPlanReportAsyncBody(string reportInfo)
        {
            this.reportInfo = reportInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReportAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReportAsyncResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponseBody Body;
        
        public getPlanReportAsyncResponse()
        {
        }
        
        public getPlanReportAsyncResponse(TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportAsyncResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getPlanReportAsyncResponseBody()
        {
        }
        
        public getPlanReportAsyncResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReport
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReport", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportBody Body;
        
        public getPlanReport()
        {
        }
        
        public getPlanReport(TRS.IT.SI.Services.wsReports.getPlanReportBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reportInfo;
        
        public getPlanReportBody()
        {
        }
        
        public getPlanReportBody(string reportInfo)
        {
            this.reportInfo = reportInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlanReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlanReportResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getPlanReportResponseBody Body;
        
        public getPlanReportResponse()
        {
        }
        
        public getPlanReportResponse(TRS.IT.SI.Services.wsReports.getPlanReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getPlanReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getPlanReportResponseBody()
        {
        }
        
        public getPlanReportResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSourceList
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSourceList", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getSourceListBody Body;
        
        public getSourceList()
        {
        }
        
        public getSourceList(TRS.IT.SI.Services.wsReports.getSourceListBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getSourceListBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caseNo;
        
        public getSourceListBody()
        {
        }
        
        public getSourceListBody(string caseNo)
        {
            this.caseNo = caseNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSourceListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSourceListResponse", Namespace="http://reports.businessactivity.webservices.psd.trs.com/", Order=0)]
        public TRS.IT.SI.Services.wsReports.getSourceListResponseBody Body;
        
        public getSourceListResponse()
        {
        }
        
        public getSourceListResponse(TRS.IT.SI.Services.wsReports.getSourceListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reports.businessactivity.webservices.psd.trs.com/")]
    public partial class getSourceListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSourceListResponseBody()
        {
        }
        
        public getSourceListResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ReportsBAImplPortTypeChannel : TRS.IT.SI.Services.wsReports.ReportsBAImplPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReportsBAImplPortTypeClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsReports.ReportsBAImplPortType>, TRS.IT.SI.Services.wsReports.ReportsBAImplPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportsBAImplPortTypeClient() : 
                base(ReportsBAImplPortTypeClient.GetDefaultBinding(), ReportsBAImplPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ReportsBAImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsBAImplPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportsBAImplPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ReportsBAImplPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsBAImplPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportsBAImplPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsBAImplPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportsBAImplPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsBAImplPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getFundListResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getFundList(TRS.IT.SI.Services.wsReports.getFundList request)
        {
            return base.Channel.getFundList(request);
        }
        
        public string getFundList(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getFundList inValue = new TRS.IT.SI.Services.wsReports.getFundList();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getFundListBody();
            inValue.Body.caseNo = caseNo;
            TRS.IT.SI.Services.wsReports.getFundListResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getFundList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getFundListResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getFundListAsync(TRS.IT.SI.Services.wsReports.getFundList request)
        {
            return base.Channel.getFundListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getFundListResponse> getFundListAsync(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getFundList inValue = new TRS.IT.SI.Services.wsReports.getFundList();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getFundListBody();
            inValue.Body.caseNo = caseNo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getFundListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getDistributionTypesResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getDistributionTypes(TRS.IT.SI.Services.wsReports.getDistributionTypes request)
        {
            return base.Channel.getDistributionTypes(request);
        }
        
        public string getDistributionTypes(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getDistributionTypes inValue = new TRS.IT.SI.Services.wsReports.getDistributionTypes();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getDistributionTypesBody();
            inValue.Body.caseNo = caseNo;
            TRS.IT.SI.Services.wsReports.getDistributionTypesResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getDistributionTypes(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDistributionTypesResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getDistributionTypesAsync(TRS.IT.SI.Services.wsReports.getDistributionTypes request)
        {
            return base.Channel.getDistributionTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDistributionTypesResponse> getDistributionTypesAsync(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getDistributionTypes inValue = new TRS.IT.SI.Services.wsReports.getDistributionTypes();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getDistributionTypesBody();
            inValue.Body.caseNo = caseNo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getDistributionTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getStatementPeriodEndData(TRS.IT.SI.Services.wsReports.getStatementPeriodEndData request)
        {
            return base.Channel.getStatementPeriodEndData(request);
        }
        
        public string getStatementPeriodEndData(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getStatementPeriodEndData inValue = new TRS.IT.SI.Services.wsReports.getStatementPeriodEndData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataBody();
            inValue.Body.caseNo = caseNo;
            TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getStatementPeriodEndData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getStatementPeriodEndDataAsync(TRS.IT.SI.Services.wsReports.getStatementPeriodEndData request)
        {
            return base.Channel.getStatementPeriodEndDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataResponse> getStatementPeriodEndDataAsync(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getStatementPeriodEndData inValue = new TRS.IT.SI.Services.wsReports.getStatementPeriodEndData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getStatementPeriodEndDataBody();
            inValue.Body.caseNo = caseNo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getStatementPeriodEndDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getPlanReportDataResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReportData(TRS.IT.SI.Services.wsReports.getPlanReportData request)
        {
            return base.Channel.getPlanReportData(request);
        }
        
        public string getPlanReportData(string reportInfo, string returnFormat)
        {
            TRS.IT.SI.Services.wsReports.getPlanReportData inValue = new TRS.IT.SI.Services.wsReports.getPlanReportData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportDataBody();
            inValue.Body.reportInfo = reportInfo;
            inValue.Body.returnFormat = returnFormat;
            TRS.IT.SI.Services.wsReports.getPlanReportDataResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReportData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportDataResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReportDataAsync(TRS.IT.SI.Services.wsReports.getPlanReportData request)
        {
            return base.Channel.getPlanReportDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportDataResponse> getPlanReportDataAsync(string reportInfo, string returnFormat)
        {
            TRS.IT.SI.Services.wsReports.getPlanReportData inValue = new TRS.IT.SI.Services.wsReports.getPlanReportData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportDataBody();
            inValue.Body.reportInfo = reportInfo;
            inValue.Body.returnFormat = returnFormat;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReportDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.generateReportResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.generateReport(TRS.IT.SI.Services.wsReports.generateReport request)
        {
            return base.Channel.generateReport(request);
        }
        
        public string generateReport(string reportRequest)
        {
            TRS.IT.SI.Services.wsReports.generateReport inValue = new TRS.IT.SI.Services.wsReports.generateReport();
            inValue.Body = new TRS.IT.SI.Services.wsReports.generateReportBody();
            inValue.Body.reportRequest = reportRequest;
            TRS.IT.SI.Services.wsReports.generateReportResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).generateReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.generateReportResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.generateReportAsync(TRS.IT.SI.Services.wsReports.generateReport request)
        {
            return base.Channel.generateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.generateReportResponse> generateReportAsync(string reportRequest)
        {
            TRS.IT.SI.Services.wsReports.generateReport inValue = new TRS.IT.SI.Services.wsReports.generateReport();
            inValue.Body = new TRS.IT.SI.Services.wsReports.generateReportBody();
            inValue.Body.reportRequest = reportRequest;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).generateReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getDrillDownDataResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getDrillDownData(TRS.IT.SI.Services.wsReports.getDrillDownData request)
        {
            return base.Channel.getDrillDownData(request);
        }
        
        public string getDrillDownData(string reportInfo)
        {
            TRS.IT.SI.Services.wsReports.getDrillDownData inValue = new TRS.IT.SI.Services.wsReports.getDrillDownData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getDrillDownDataBody();
            inValue.Body.reportInfo = reportInfo;
            TRS.IT.SI.Services.wsReports.getDrillDownDataResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getDrillDownData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDrillDownDataResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getDrillDownDataAsync(TRS.IT.SI.Services.wsReports.getDrillDownData request)
        {
            return base.Channel.getDrillDownDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getDrillDownDataResponse> getDrillDownDataAsync(string reportInfo)
        {
            TRS.IT.SI.Services.wsReports.getDrillDownData inValue = new TRS.IT.SI.Services.wsReports.getDrillDownData();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getDrillDownDataBody();
            inValue.Body.reportInfo = reportInfo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getDrillDownDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReportAsync(TRS.IT.SI.Services.wsReports.getPlanReportAsync request)
        {
            return base.Channel.getPlanReportAsync(request);
        }
        
        public string getPlanReportAsync(string reportInfo)
        {
            TRS.IT.SI.Services.wsReports.getPlanReportAsync inValue = new TRS.IT.SI.Services.wsReports.getPlanReportAsync();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportAsyncBody();
            inValue.Body.reportInfo = reportInfo;
            TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReportAsync(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReportAsyncAsync(TRS.IT.SI.Services.wsReports.getPlanReportAsync request)
        {
            return base.Channel.getPlanReportAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportAsyncResponse> getPlanReportAsyncAsync(string reportInfo)
        {
            TRS.IT.SI.Services.wsReports.getPlanReportAsync inValue = new TRS.IT.SI.Services.wsReports.getPlanReportAsync();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportAsyncBody();
            inValue.Body.reportInfo = reportInfo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReportAsyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getPlanReportResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReport(TRS.IT.SI.Services.wsReports.getPlanReport request)
        {
            return base.Channel.getPlanReport(request);
        }
        
        public string getPlanReport(string reportInfo)
        {
            TRS.IT.SI.Services.wsReports.getPlanReport inValue = new TRS.IT.SI.Services.wsReports.getPlanReport();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportBody();
            inValue.Body.reportInfo = reportInfo;
            TRS.IT.SI.Services.wsReports.getPlanReportResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getPlanReportAsync(TRS.IT.SI.Services.wsReports.getPlanReport request)
        {
            return base.Channel.getPlanReportAsync(request);
        }
        
        //public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getPlanReportResponse> getPlanReportAsync(string reportInfo)
        //{
        //    TRS.IT.SI.Services.wsReports.getPlanReport inValue = new TRS.IT.SI.Services.wsReports.getPlanReport();
        //    inValue.Body = new TRS.IT.SI.Services.wsReports.getPlanReportBody();
        //    inValue.Body.reportInfo = reportInfo;
        //    return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getPlanReportAsync(inValue);
        //}
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsReports.getSourceListResponse TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getSourceList(TRS.IT.SI.Services.wsReports.getSourceList request)
        {
            return base.Channel.getSourceList(request);
        }
        
        public string getSourceList(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getSourceList inValue = new TRS.IT.SI.Services.wsReports.getSourceList();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getSourceListBody();
            inValue.Body.caseNo = caseNo;
            TRS.IT.SI.Services.wsReports.getSourceListResponse retVal = ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getSourceList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getSourceListResponse> TRS.IT.SI.Services.wsReports.ReportsBAImplPortType.getSourceListAsync(TRS.IT.SI.Services.wsReports.getSourceList request)
        {
            return base.Channel.getSourceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsReports.getSourceListResponse> getSourceListAsync(string caseNo)
        {
            TRS.IT.SI.Services.wsReports.getSourceList inValue = new TRS.IT.SI.Services.wsReports.getSourceList();
            inValue.Body = new TRS.IT.SI.Services.wsReports.getSourceListBody();
            inValue.Body.caseNo = caseNo;
            return ((TRS.IT.SI.Services.wsReports.ReportsBAImplPortType)(this)).getSourceListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportsBAImplPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportsBAImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://psdwebsvctst.us.aegon.com/com.trs.psd.webservices/ReportService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReportsBAImplPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ReportsBAImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReportsBAImplPortTypeClient.GetEndpointAddress(EndpointConfiguration.ReportsBAImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ReportsBAImplPort,
        }
    }
}
