//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsDocumentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TRSWebServices/DocumentService/", ConfigurationName="TRS.IT.SI.Services.wsDocumentService.DocumentServiceSoap")]
    public interface DocumentServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/GetDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsDocumentService.DocumentResponse GetDocument(TRS.IT.SI.Services.wsDocumentService.DocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/GetDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.DocumentResponse> GetDocumentAsync(TRS.IT.SI.Services.wsDocumentService.DocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/IndexDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsDocumentService.IndexDocumentResponse IndexDocument(TRS.IT.SI.Services.wsDocumentService.IndexDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/IndexDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.IndexDocumentResponse> IndexDocumentAsync(TRS.IT.SI.Services.wsDocumentService.IndexDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/ImportFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsDocumentService.ImportFileResponse ImportFile(TRS.IT.SI.Services.wsDocumentService.ImportFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/ImportFile", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.ImportFileResponse> ImportFileAsync(TRS.IT.SI.Services.wsDocumentService.ImportFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/GetProcessID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsDocumentService.ProcessIDResponse GetProcessID(TRS.IT.SI.Services.wsDocumentService.ProcessIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/GetProcessID", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.ProcessIDResponse> GetProcessIDAsync(TRS.IT.SI.Services.wsDocumentService.ProcessIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/RefreshApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        string RefreshApplication(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServices/DocumentService/RefreshApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RefreshApplicationAsync(string request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class DocumentRequest
    {
        
        private string contractIDField;
        
        private string subIDField;
        
        private string sSNField;
        
        private string certificateField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private string tpaIDField;
        
        private string dateIDField;
        
        private string accountantIDField;
        
        private int[] docIDsField;
        
        private int[] docTypeCodesField;
        
        private string[] docTypeNamesField;
        
        private string[] docPackageNamesField;
        
        private string[] trackNumbersField;
        
        private string batchIDField;
        
        private string batchPrefixField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private bool includeAllSubIDsField;
        
        private bool includeAllSSNsField;
        
        private bool includeDeletedDocsField;
        
        private bool includeOnlyLatestDocField;
        
        private bool excludeRequiredFieldsField;
        
        private bool convertToPDFField;
        
        private string userIDField;
        
        private string passwordField;
        
        private int authorityLevelCodeField;
        
        private string destinationPathField;
        
        private string systemNameField;
        
        private string sourceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TpaID
        {
            get
            {
                return this.tpaIDField;
            }
            set
            {
                this.tpaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DateID
        {
            get
            {
                return this.dateIDField;
            }
            set
            {
                this.dateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AccountantID
        {
            get
            {
                return this.accountantIDField;
            }
            set
            {
                this.accountantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public int[] DocIDs
        {
            get
            {
                return this.docIDsField;
            }
            set
            {
                this.docIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public int[] DocTypeCodes
        {
            get
            {
                return this.docTypeCodesField;
            }
            set
            {
                this.docTypeCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public string[] DocTypeNames
        {
            get
            {
                return this.docTypeNamesField;
            }
            set
            {
                this.docTypeNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public string[] DocPackageNames
        {
            get
            {
                return this.docPackageNamesField;
            }
            set
            {
                this.docPackageNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public string[] TrackNumbers
        {
            get
            {
                return this.trackNumbersField;
            }
            set
            {
                this.trackNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BatchID
        {
            get
            {
                return this.batchIDField;
            }
            set
            {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BatchPrefix
        {
            get
            {
                return this.batchPrefixField;
            }
            set
            {
                this.batchPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IncludeAllSubIDs
        {
            get
            {
                return this.includeAllSubIDsField;
            }
            set
            {
                this.includeAllSubIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool IncludeAllSSNs
        {
            get
            {
                return this.includeAllSSNsField;
            }
            set
            {
                this.includeAllSSNsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool IncludeDeletedDocs
        {
            get
            {
                return this.includeDeletedDocsField;
            }
            set
            {
                this.includeDeletedDocsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool IncludeOnlyLatestDoc
        {
            get
            {
                return this.includeOnlyLatestDocField;
            }
            set
            {
                this.includeOnlyLatestDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool ExcludeRequiredFields
        {
            get
            {
                return this.excludeRequiredFieldsField;
            }
            set
            {
                this.excludeRequiredFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool ConvertToPDF
        {
            get
            {
                return this.convertToPDFField;
            }
            set
            {
                this.convertToPDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int AuthorityLevelCode
        {
            get
            {
                return this.authorityLevelCodeField;
            }
            set
            {
                this.authorityLevelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string DestinationPath
        {
            get
            {
                return this.destinationPathField;
            }
            set
            {
                this.destinationPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class ProcessIDRequest
    {
        
        private int processIDField;
        
        private string systemNameField;
        
        private string sourceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProcessID
        {
            get
            {
                return this.processIDField;
            }
            set
            {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class ImportFile
    {
        
        private int processIDField;
        
        private int docTypeCodeField;
        
        private string docTypeNameField;
        
        private int batchTypeCodeField;
        
        private string batchPrefixField;
        
        private string docClassNameField;
        
        private int queueCodeField;
        
        private int priorityCodeField;
        
        private int statusCodeField;
        
        private string statusDetailField;
        
        private string userIDField;
        
        private string contractIDField;
        
        private string subIDField;
        
        private string sSNField;
        
        private string certificateField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private string tpaIDField;
        
        private string dateIDField;
        
        private string accountantIDField;
        
        private string nameField;
        
        private string trackNumberField;
        
        private System.DateTime wmsTimeReceivedField;
        
        private string fileNameField;
        
        private string filePathField;
        
        private int filePagesField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProcessID
        {
            get
            {
                return this.processIDField;
            }
            set
            {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocTypeName
        {
            get
            {
                return this.docTypeNameField;
            }
            set
            {
                this.docTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BatchTypeCode
        {
            get
            {
                return this.batchTypeCodeField;
            }
            set
            {
                this.batchTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BatchPrefix
        {
            get
            {
                return this.batchPrefixField;
            }
            set
            {
                this.batchPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocClassName
        {
            get
            {
                return this.docClassNameField;
            }
            set
            {
                this.docClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int QueueCode
        {
            get
            {
                return this.queueCodeField;
            }
            set
            {
                this.queueCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PriorityCode
        {
            get
            {
                return this.priorityCodeField;
            }
            set
            {
                this.priorityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StatusDetail
        {
            get
            {
                return this.statusDetailField;
            }
            set
            {
                this.statusDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TpaID
        {
            get
            {
                return this.tpaIDField;
            }
            set
            {
                this.tpaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DateID
        {
            get
            {
                return this.dateIDField;
            }
            set
            {
                this.dateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AccountantID
        {
            get
            {
                return this.accountantIDField;
            }
            set
            {
                this.accountantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TrackNumber
        {
            get
            {
                return this.trackNumberField;
            }
            set
            {
                this.trackNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.DateTime WmsTimeReceived
        {
            get
            {
                return this.wmsTimeReceivedField;
            }
            set
            {
                this.wmsTimeReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FilePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int FilePages
        {
            get
            {
                return this.filePagesField;
            }
            set
            {
                this.filePagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=26)]
        public byte[] FileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class ImportFileRequest
    {
        
        private E_ProcessType processTypeField;
        
        private int folderIDField;
        
        private System.DateTime pendDateField;
        
        private string systemNameField;
        
        private string sourceNameField;
        
        private ImportFile[] importFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public E_ProcessType ProcessType
        {
            get
            {
                return this.processTypeField;
            }
            set
            {
                this.processTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FolderID
        {
            get
            {
                return this.folderIDField;
            }
            set
            {
                this.folderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime PendDate
        {
            get
            {
                return this.pendDateField;
            }
            set
            {
                this.pendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public ImportFile[] ImportFiles
        {
            get
            {
                return this.importFilesField;
            }
            set
            {
                this.importFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public enum E_ProcessType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        FileImport,
        
        /// <remarks/>
        SystemOutput,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class IndexDocumentRequest
    {
        
        private string userIDField;
        
        private string systemNameField;
        
        private string sourceNameField;
        
        private IndexDocument[] indexDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public IndexDocument[] IndexDocuments
        {
            get
            {
                return this.indexDocumentsField;
            }
            set
            {
                this.indexDocumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class IndexDocument : Document
    {
        
        private string statusDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusDetail
        {
            get
            {
                return this.statusDetailField;
            }
            set
            {
                this.statusDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndexDocument))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class Document
    {
        
        private string contractIDField;
        
        private string subIDField;
        
        private string sSNField;
        
        private string certificateField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private string tpaIDField;
        
        private string dateIDField;
        
        private string accountantIDField;
        
        private string nameField;
        
        private string trackNumberField;
        
        private int docIDField;
        
        private int docTypeCodeField;
        
        private string docTypeNameField;
        
        private string docClassNameField;
        
        private string docTypeField;
        
        private string docFormatField;
        
        private System.DateTime dateReceivedField;
        
        private System.DateTime wmsTimeReceivedField;
        
        private System.DateTime systemTimeReceivedField;
        
        private int pagesField;
        
        private string batchIDField;
        
        private string barcodeTextField;
        
        private int restoreDocIDField;
        
        private string urlField;
        
        private string sourcePathField;
        
        private string destinationPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TpaID
        {
            get
            {
                return this.tpaIDField;
            }
            set
            {
                this.tpaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DateID
        {
            get
            {
                return this.dateIDField;
            }
            set
            {
                this.dateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AccountantID
        {
            get
            {
                return this.accountantIDField;
            }
            set
            {
                this.accountantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TrackNumber
        {
            get
            {
                return this.trackNumberField;
            }
            set
            {
                this.trackNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DocID
        {
            get
            {
                return this.docIDField;
            }
            set
            {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DocTypeName
        {
            get
            {
                return this.docTypeNameField;
            }
            set
            {
                this.docTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DocClassName
        {
            get
            {
                return this.docClassNameField;
            }
            set
            {
                this.docClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DocFormat
        {
            get
            {
                return this.docFormatField;
            }
            set
            {
                this.docFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime DateReceived
        {
            get
            {
                return this.dateReceivedField;
            }
            set
            {
                this.dateReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime WmsTimeReceived
        {
            get
            {
                return this.wmsTimeReceivedField;
            }
            set
            {
                this.wmsTimeReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime SystemTimeReceived
        {
            get
            {
                return this.systemTimeReceivedField;
            }
            set
            {
                this.systemTimeReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int Pages
        {
            get
            {
                return this.pagesField;
            }
            set
            {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BatchID
        {
            get
            {
                return this.batchIDField;
            }
            set
            {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BarcodeText
        {
            get
            {
                return this.barcodeTextField;
            }
            set
            {
                this.barcodeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int RestoreDocID
        {
            get
            {
                return this.restoreDocIDField;
            }
            set
            {
                this.restoreDocIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string SourcePath
        {
            get
            {
                return this.sourcePathField;
            }
            set
            {
                this.sourcePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DestinationPath
        {
            get
            {
                return this.destinationPathField;
            }
            set
            {
                this.destinationPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class ErrorInfo
    {
        
        private int numberField;
        
        private string descriptionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessIDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndexDocumentResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class TWS_Response
    {
        
        private ErrorInfo[] errorsField;
        
        private string confirmationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ErrorInfo[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConfirmationNumber
        {
            get
            {
                return this.confirmationNumberField;
            }
            set
            {
                this.confirmationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class ProcessIDResponse : TWS_Response
    {
        
        private int processIDField;
        
        private string filePathField;
        
        private int docTypeCodeField;
        
        private int batchTypeCodeField;
        
        private string batchPrefixField;
        
        private string docClassNameField;
        
        private int queueCodeField;
        
        private int priorityCodeField;
        
        private int statusCodeField;
        
        private string userIDField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProcessID
        {
            get
            {
                return this.processIDField;
            }
            set
            {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FilePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BatchTypeCode
        {
            get
            {
                return this.batchTypeCodeField;
            }
            set
            {
                this.batchTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BatchPrefix
        {
            get
            {
                return this.batchPrefixField;
            }
            set
            {
                this.batchPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocClassName
        {
            get
            {
                return this.docClassNameField;
            }
            set
            {
                this.docClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int QueueCode
        {
            get
            {
                return this.queueCodeField;
            }
            set
            {
                this.queueCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PriorityCode
        {
            get
            {
                return this.priorityCodeField;
            }
            set
            {
                this.priorityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class ImportFileResponse : TWS_Response
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class IndexDocumentResponse : TWS_Response
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServices/DocumentService/")]
    public partial class DocumentResponse : TWS_Response
    {
        
        private Document[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Document[] Documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DocumentServiceSoapChannel : TRS.IT.SI.Services.wsDocumentService.DocumentServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DocumentServiceSoapClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsDocumentService.DocumentServiceSoap>, TRS.IT.SI.Services.wsDocumentService.DocumentServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocumentServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DocumentServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), DocumentServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocumentServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocumentServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.wsDocumentService.DocumentResponse GetDocument(TRS.IT.SI.Services.wsDocumentService.DocumentRequest request)
        {
            return base.Channel.GetDocument(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.DocumentResponse> GetDocumentAsync(TRS.IT.SI.Services.wsDocumentService.DocumentRequest request)
        {
            return base.Channel.GetDocumentAsync(request);
        }
        
        public TRS.IT.SI.Services.wsDocumentService.IndexDocumentResponse IndexDocument(TRS.IT.SI.Services.wsDocumentService.IndexDocumentRequest request)
        {
            return base.Channel.IndexDocument(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.IndexDocumentResponse> IndexDocumentAsync(TRS.IT.SI.Services.wsDocumentService.IndexDocumentRequest request)
        {
            return base.Channel.IndexDocumentAsync(request);
        }
        
        public TRS.IT.SI.Services.wsDocumentService.ImportFileResponse ImportFile(TRS.IT.SI.Services.wsDocumentService.ImportFileRequest request)
        {
            return base.Channel.ImportFile(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.ImportFileResponse> ImportFileAsync(TRS.IT.SI.Services.wsDocumentService.ImportFileRequest request)
        {
            return base.Channel.ImportFileAsync(request);
        }
        
        public TRS.IT.SI.Services.wsDocumentService.ProcessIDResponse GetProcessID(TRS.IT.SI.Services.wsDocumentService.ProcessIDRequest request)
        {
            return base.Channel.GetProcessID(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsDocumentService.ProcessIDResponse> GetProcessIDAsync(TRS.IT.SI.Services.wsDocumentService.ProcessIDRequest request)
        {
            return base.Channel.GetProcessIDAsync(request);
        }
        
        public string RefreshApplication(string request)
        {
            return base.Channel.RefreshApplication(request);
        }
        
        public System.Threading.Tasks.Task<string> RefreshApplicationAsync(string request)
        {
            return base.Channel.RefreshApplicationAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DocumentServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wms-document-service-tst.us.aegon.com:8443/DocumentService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DocumentServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wms-document-service-tst.us.aegon.com:8443/DocumentService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DocumentServiceSoap,
            
            DocumentServiceSoap12,
        }
    }
}
