//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsMessage
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transamerica.com/LosAngeles/", ConfigurationName="TRS.IT.SI.Services.wsMessage.MessageServiceSoap")]
    public interface MessageServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/SendMessageCenterMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsMessage.TWS_Response SendMessageCenterMessage(TRS.IT.SI.Services.wsMessage.MessageCenter oMessageCtr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/SendMessageCenterMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.TWS_Response> SendMessageCenterMessageAsync(TRS.IT.SI.Services.wsMessage.MessageCenter oMessageCtr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetMessageData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsMessage.KeyValueData GetMessageData(TRS.IT.SI.Services.wsMessage.MessageData oMessageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetMessageData", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.KeyValueData> GetMessageDataAsync(TRS.IT.SI.Services.wsMessage.MessageData oMessageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/SendWebMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsMessage.TWS_Response SendWebMessages(string InLogin_xml, TRS.IT.SI.Services.wsMessage.webMessage oWebMsg, string ContractID, string SubID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/SendWebMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.TWS_Response> SendWebMessagesAsync(string InLogin_xml, TRS.IT.SI.Services.wsMessage.webMessage oWebMsg, string ContractID, string SubID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class MessageCenter
    {
        
        private string in_LoginIDField;
        
        private E_MessageCenter_Audience audienceField;
        
        private string subjectField;
        
        private string messageField;
        
        private string fromField;
        
        private string customDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string In_LoginID
        {
            get
            {
                return this.in_LoginIDField;
            }
            set
            {
                this.in_LoginIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public E_MessageCenter_Audience Audience
        {
            get
            {
                return this.audienceField;
            }
            set
            {
                this.audienceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CustomData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public enum E_MessageCenter_Audience
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("104")]
        Item104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9999")]
        Item9999,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99999")]
        Item99999,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class Identification
    {
        
        private string contractIdField;
        
        private string subIdField;
        
        private string planNameField;
        
        private string sSNField;
        
        private string cRMField;
        
        private string sPOCField;
        
        private string partnerIdField;
        
        private string serviceTypeField;
        
        private string contractStatusField;
        
        private string passPMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContractId
        {
            get
            {
                return this.contractIdField;
            }
            set
            {
                this.contractIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubId
        {
            get
            {
                return this.subIdField;
            }
            set
            {
                this.subIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlanName
        {
            get
            {
                return this.planNameField;
            }
            set
            {
                this.planNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CRM
        {
            get
            {
                return this.cRMField;
            }
            set
            {
                this.cRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SPOC
        {
            get
            {
                return this.sPOCField;
            }
            set
            {
                this.sPOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContractStatus
        {
            get
            {
                return this.contractStatusField;
            }
            set
            {
                this.contractStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PassPM
        {
            get
            {
                return this.passPMField;
            }
            set
            {
                this.passPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class Attachment
    {
        
        private string dataField;
        
        private string fileNameField;
        
        private string fileTypeField;
        
        private string filePathField;
        
        private int fileSizeField;
        
        private string promptFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FileSize
        {
            get
            {
                return this.fileSizeField;
            }
            set
            {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PromptFileName
        {
            get
            {
                return this.promptFileNameField;
            }
            set
            {
                this.promptFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class MsgData
    {
        
        private string bodyField;
        
        private Attachment[] attachmentsField;
        
        private Identification identificationField;
        
        private string emailFormatField;
        
        private string replyToEmailField;
        
        private long replyToInloginIdField;
        
        private bool replyAllowedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Attachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Identification Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailFormat
        {
            get
            {
                return this.emailFormatField;
            }
            set
            {
                this.emailFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReplyToEmail
        {
            get
            {
                return this.replyToEmailField;
            }
            set
            {
                this.replyToEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ReplyToInloginId
        {
            get
            {
                return this.replyToInloginIdField;
            }
            set
            {
                this.replyToInloginIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ReplyAllowed
        {
            get
            {
                return this.replyAllowedField;
            }
            set
            {
                this.replyAllowedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class Addr
    {
        
        private string emailAddressField;
        
        private int inloginIdField;
        
        private webMsgEmailScopeEnum emailScopeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int InloginId
        {
            get
            {
                return this.inloginIdField;
            }
            set
            {
                this.inloginIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public webMsgEmailScopeEnum EmailScope
        {
            get
            {
                return this.emailScopeField;
            }
            set
            {
                this.emailScopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public enum webMsgEmailScopeEnum
    {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class ToAddr
    {
        
        private Addr[] addrField;
        
        private webMsgBroadCastEnum broadCastField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Addr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Addr[] Addr
        {
            get
            {
                return this.addrField;
            }
            set
            {
                this.addrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public webMsgBroadCastEnum BroadCast
        {
            get
            {
                return this.broadCastField;
            }
            set
            {
                this.broadCastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public enum webMsgBroadCastEnum
    {
        
        /// <remarks/>
        ToOneOrFew,
        
        /// <remarks/>
        Global,
        
        /// <remarks/>
        PlanLevel,
        
        /// <remarks/>
        ToMany,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class webMessage
    {
        
        private int msgIdField;
        
        private int folderIdField;
        
        private string subjectField;
        
        private string createByField;
        
        private string fromAddressField;
        
        private ToAddr toAddressField;
        
        private MsgData msgDataField;
        
        private string msgTypeField;
        
        private int attachmentCountField;
        
        private string createDtField;
        
        private string expireDtField;
        
        private string sendNotificationField;
        
        private string notificationDtField;
        
        private string linkKeyField;
        
        private string msgSourceField;
        
        private string senderInLoginIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int MsgId
        {
            get
            {
                return this.msgIdField;
            }
            set
            {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int FolderId
        {
            get
            {
                return this.folderIdField;
            }
            set
            {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CreateBy
        {
            get
            {
                return this.createByField;
            }
            set
            {
                this.createByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FromAddress
        {
            get
            {
                return this.fromAddressField;
            }
            set
            {
                this.fromAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ToAddr ToAddress
        {
            get
            {
                return this.toAddressField;
            }
            set
            {
                this.toAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public MsgData MsgData
        {
            get
            {
                return this.msgDataField;
            }
            set
            {
                this.msgDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MsgType
        {
            get
            {
                return this.msgTypeField;
            }
            set
            {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int AttachmentCount
        {
            get
            {
                return this.attachmentCountField;
            }
            set
            {
                this.attachmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CreateDt
        {
            get
            {
                return this.createDtField;
            }
            set
            {
                this.createDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ExpireDt
        {
            get
            {
                return this.expireDtField;
            }
            set
            {
                this.expireDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SendNotification
        {
            get
            {
                return this.sendNotificationField;
            }
            set
            {
                this.sendNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string NotificationDt
        {
            get
            {
                return this.notificationDtField;
            }
            set
            {
                this.notificationDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string LinkKey
        {
            get
            {
                return this.linkKeyField;
            }
            set
            {
                this.linkKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MsgSource
        {
            get
            {
                return this.msgSourceField;
            }
            set
            {
                this.msgSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SenderInLoginId
        {
            get
            {
                return this.senderInLoginIdField;
            }
            set
            {
                this.senderInLoginIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class MessageData
    {
        
        private string contractIDField;
        
        private string subIDField;
        
        private string sSNField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private KeyValue[] requestedKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestedKeys", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public KeyValue[] RequestedKeys
        {
            get
            {
                return this.requestedKeysField;
            }
            set
            {
                this.requestedKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class KeyValue
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class ErrorInfo
    {
        
        private int numberField;
        
        private string descriptionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyValueData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class TWS_Response
    {
        
        private ErrorInfo[] errorsField;
        
        private string confirmationNumberField;
        
        private string[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ErrorInfo[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConfirmationNumber
        {
            get
            {
                return this.confirmationNumberField;
            }
            set
            {
                this.confirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warnings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] Warnings
        {
            get
            {
                return this.warningsField;
            }
            set
            {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class KeyValueData : TWS_Response
    {
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public KeyValue[] KeyValues
        {
            get
            {
                return this.keyValuesField;
            }
            set
            {
                this.keyValuesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface MessageServiceSoapChannel : TRS.IT.SI.Services.wsMessage.MessageServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsMessage.MessageServiceSoap>, TRS.IT.SI.Services.wsMessage.MessageServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MessageServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.wsMessage.TWS_Response SendMessageCenterMessage(TRS.IT.SI.Services.wsMessage.MessageCenter oMessageCtr)
        {
            return base.Channel.SendMessageCenterMessage(oMessageCtr);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.TWS_Response> SendMessageCenterMessageAsync(TRS.IT.SI.Services.wsMessage.MessageCenter oMessageCtr)
        {
            return base.Channel.SendMessageCenterMessageAsync(oMessageCtr);
        }
        
        public TRS.IT.SI.Services.wsMessage.KeyValueData GetMessageData(TRS.IT.SI.Services.wsMessage.MessageData oMessageData)
        {
            return base.Channel.GetMessageData(oMessageData);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.KeyValueData> GetMessageDataAsync(TRS.IT.SI.Services.wsMessage.MessageData oMessageData)
        {
            return base.Channel.GetMessageDataAsync(oMessageData);
        }
        
        public TRS.IT.SI.Services.wsMessage.TWS_Response SendWebMessages(string InLogin_xml, TRS.IT.SI.Services.wsMessage.webMessage oWebMsg, string ContractID, string SubID)
        {
            return base.Channel.SendWebMessages(InLogin_xml, oWebMsg, ContractID, SubID);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsMessage.TWS_Response> SendWebMessagesAsync(string InLogin_xml, TRS.IT.SI.Services.wsMessage.webMessage oWebMsg, string ContractID, string SubID)
        {
            return base.Channel.SendWebMessagesAsync(InLogin_xml, oWebMsg, ContractID, SubID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/MessageService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/MessageService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MessageServiceSoap,
            
            MessageServiceSoap12,
        }
    }
}
