//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsFundContractsService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transamerica.com/LosAngeles/", ConfigurationName="TRS.IT.SI.Services.wsFundContractsService.FundContractsServiceSoap")]
    public interface FundContractsServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetContracts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        TRS.IT.SI.Services.wsFundContractsService.FundContracts GetContracts(string contract_id, string sub_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetContracts", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsFundContractsService.FundContracts> GetContractsAsync(string contract_id, string sub_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/AddDeleteMultiContracts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        string AddDeleteMultiContracts(TRS.IT.SI.Services.wsFundContractsService.AddDeleteMultiContractsTable table, string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/AddDeleteMultiContracts", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddDeleteMultiContractsAsync(TRS.IT.SI.Services.wsFundContractsService.AddDeleteMultiContractsTable table, string user_id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transamerica.com/LosAngeles/")]
    public partial class FundContracts : BaseEntity
    {
        
        private FundContractsData[] contractCollectionField;
        
        private bool succeededField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractCollection", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FundContractsData[] ContractCollection
        {
            get
            {
                return this.contractCollectionField;
            }
            set
            {
                this.contractCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Succeeded
        {
            get
            {
                return this.succeededField;
            }
            set
            {
                this.succeededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transamerica.com/LosAngeles/")]
    public partial class FundContractsData : BaseEntity
    {
        
        private string contractIDField;
        
        private string subIDField;
        
        private int statementIDField;
        
        private int individualIDField;
        
        private int addressIDField;
        
        private bool contactTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int StatementID
        {
            get
            {
                return this.statementIDField;
            }
            set
            {
                this.statementIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int IndividualID
        {
            get
            {
                return this.individualIDField;
            }
            set
            {
                this.individualIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int AddressID
        {
            get
            {
                return this.addressIDField;
            }
            set
            {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool ContactType
        {
            get
            {
                return this.contactTypeField;
            }
            set
            {
                this.contactTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FundContractsData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FundContracts))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transamerica.com/LosAngeles/")]
    public abstract partial class BaseEntity
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transamerica.com/LosAngeles/")]
    public partial class AddDeleteMultiContractsTable
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface FundContractsServiceSoapChannel : TRS.IT.SI.Services.wsFundContractsService.FundContractsServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class FundContractsServiceSoapClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsFundContractsService.FundContractsServiceSoap>, TRS.IT.SI.Services.wsFundContractsService.FundContractsServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FundContractsServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FundContractsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), FundContractsServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FundContractsServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FundContractsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FundContractsServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FundContractsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FundContractsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.wsFundContractsService.FundContracts GetContracts(string contract_id, string sub_id)
        {
            return base.Channel.GetContracts(contract_id, sub_id);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsFundContractsService.FundContracts> GetContractsAsync(string contract_id, string sub_id)
        {
            return base.Channel.GetContractsAsync(contract_id, sub_id);
        }
        
        public string AddDeleteMultiContracts(TRS.IT.SI.Services.wsFundContractsService.AddDeleteMultiContractsTable table, string user_id)
        {
            return base.Channel.AddDeleteMultiContracts(table, user_id);
        }
        
        public System.Threading.Tasks.Task<string> AddDeleteMultiContractsAsync(TRS.IT.SI.Services.wsFundContractsService.AddDeleteMultiContractsTable table, string user_id)
        {
            return base.Channel.AddDeleteMultiContractsAsync(table, user_id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FundContractsServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FundContractsServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FundContractsServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/PegasysSOA/FundContractsService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FundContractsServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/PegasysSOA/FundContractsService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FundContractsServiceSoap,
            
            FundContractsServiceSoap12,
        }
    }
}
