// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace TRS.IT.SI.BusinessFacadeLayer.Adapters.DEMOWSPPT
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://transamerica.com/LosAngeles/", ConfigurationName = "TRS.IT.SI.BusinessFacadeLayer.Adapters.DEMOWSPPT.IDemoParticipantService")]
    public interface IDemoParticipantService
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetParticipantInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetParticipantInfoResponse")]
        string GetParticipantInfo(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetParticipantInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetParticipantInfoResponse")]
        Task<string> GetParticipantInfoAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/CancelRecurringTransfer", ReplyAction = "http://transamerica.com/LosAngeles/CancelRecurringTransferResponse")]
        string CancelRecurringTransfer(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/CancelRecurringTransfer", ReplyAction = "http://transamerica.com/LosAngeles/CancelRecurringTransferResponse")]
        Task<string> CancelRecurringTransferAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/CancelTransaction", ReplyAction = "http://transamerica.com/LosAngeles/CancelTransactionResponse")]
        string CancelTransaction(string User_ID, string ConfirmationNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/CancelTransaction", ReplyAction = "http://transamerica.com/LosAngeles/CancelTransactionResponse")]
        Task<string> CancelTransactionAsync(string User_ID, string ConfirmationNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GenerateToken", ReplyAction = "http://transamerica.com/LosAngeles/GenerateTokenResponse")]
        string GenerateToken(string User_ID, string TypeCode, string UrlReturn);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GenerateToken", ReplyAction = "http://transamerica.com/LosAngeles/GenerateTokenResponse")]
        Task<string> GenerateTokenAsync(string User_ID, string TypeCode, string UrlReturn);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetAccountSummary", ReplyAction = "http://transamerica.com/LosAngeles/GetAccountSummaryResponse")]
        string GetAccountSummary(string User_ID, string FromDate, string ToDate, int SumType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetAccountSummary", ReplyAction = "http://transamerica.com/LosAngeles/GetAccountSummaryResponse")]
        Task<string> GetAccountSummaryAsync(string User_ID, string FromDate, string ToDate, int SumType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetAllLoansData", ReplyAction = "http://transamerica.com/LosAngeles/GetAllLoansDataResponse")]
        string GetAllLoansData(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetAllLoansData", ReplyAction = "http://transamerica.com/LosAngeles/GetAllLoansDataResponse")]
        Task<string> GetAllLoansDataAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetLoanRepaymentHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetLoanRepaymentHistoryResponse")]
        string GetLoanRepaymentHistory(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetLoanRepaymentHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetLoanRepaymentHistoryResponse")]
        Task<string> GetLoanRepaymentHistoryAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPassword", ReplyAction = "http://transamerica.com/LosAngeles/GetPasswordResponse")]
        string GetPassword(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPassword", ReplyAction = "http://transamerica.com/LosAngeles/GetPasswordResponse")]
        Task<string> GetPasswordAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPendingTransactionInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetPendingTransactionInfoResponse")]
        string GetPendingTransactionInfo(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPendingTransactionInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetPendingTransactionInfoResponse")]
        Task<string> GetPendingTransactionInfoAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPersonalProfile", ReplyAction = "http://transamerica.com/LosAngeles/GetPersonalProfileResponse")]
        string GetPersonalProfile(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPersonalProfile", ReplyAction = "http://transamerica.com/LosAngeles/GetPersonalProfileResponse")]
        Task<string> GetPersonalProfileAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPlanStatus", ReplyAction = "http://transamerica.com/LosAngeles/GetPlanStatusResponse")]
        string GetPlanStatus(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetPlanStatus", ReplyAction = "http://transamerica.com/LosAngeles/GetPlanStatusResponse")]
        Task<string> GetPlanStatusAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetProcessingHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetProcessingHistoryResponse")]
        string GetProcessingHistory(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetProcessingHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetProcessingHistoryResponse")]
        Task<string> GetProcessingHistoryAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetTransactionHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetTransactionHistoryResponse")]
        string GetTransactionHistory(string User_ID, string FromDate, string ToDate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetTransactionHistory", ReplyAction = "http://transamerica.com/LosAngeles/GetTransactionHistoryResponse")]
        Task<string> GetTransactionHistoryAsync(string User_ID, string FromDate, string ToDate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RebalanceFunds", ReplyAction = "http://transamerica.com/LosAngeles/RebalanceFundsResponse")]
        string RebalanceFunds(string User_ID, string TransferFreq, string FundInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RebalanceFunds", ReplyAction = "http://transamerica.com/LosAngeles/RebalanceFundsResponse")]
        Task<string> RebalanceFundsAsync(string User_ID, string TransferFreq, string FundInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RequestLoan", ReplyAction = "http://transamerica.com/LosAngeles/RequestLoanResponse")]
        string RequestLoan(string User_ID, string LoanInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RequestLoan", ReplyAction = "http://transamerica.com/LosAngeles/RequestLoanResponse")]
        Task<string> RequestLoanAsync(string User_ID, string LoanInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RequestPinLetter", ReplyAction = "http://transamerica.com/LosAngeles/RequestPinLetterResponse")]
        string RequestPinLetter(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/RequestPinLetter", ReplyAction = "http://transamerica.com/LosAngeles/RequestPinLetterResponse")]
        Task<string> RequestPinLetterAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/StatementRequest", ReplyAction = "http://transamerica.com/LosAngeles/StatementRequestResponse")]
        string StatementRequest(string User_ID, string FromDate, string ToDate, string in_OM, string RptType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/StatementRequest", ReplyAction = "http://transamerica.com/LosAngeles/StatementRequestResponse")]
        Task<string> StatementRequestAsync(string User_ID, string FromDate, string ToDate, string in_OM, string RptType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/TransferFunds", ReplyAction = "http://transamerica.com/LosAngeles/TransferFundsResponse")]
        string TransferFunds(string User_ID, string FundTransfer);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/TransferFunds", ReplyAction = "http://transamerica.com/LosAngeles/TransferFundsResponse")]
        Task<string> TransferFundsAsync(string User_ID, string FundTransfer);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateCatchupContributions", ReplyAction = "http://transamerica.com/LosAngeles/UpdateCatchupContributionsResponse")]
        string UpdateCatchupContributions(string User_ID, string CatchupInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateCatchupContributions", ReplyAction = "http://transamerica.com/LosAngeles/UpdateCatchupContributionsResponse")]
        Task<string> UpdateCatchupContributionsAsync(string User_ID, string CatchupInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateDeferralContributions", ReplyAction = "http://transamerica.com/LosAngeles/UpdateDeferralContributionsResponse")]
        string UpdateDeferralContributions(string User_ID, string DeferralInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateDeferralContributions", ReplyAction = "http://transamerica.com/LosAngeles/UpdateDeferralContributionsResponse")]
        Task<string> UpdateDeferralContributionsAsync(string User_ID, string DeferralInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateInvestmentElections", ReplyAction = "http://transamerica.com/LosAngeles/UpdateInvestmentElectionsResponse")]
        string UpdateInvestmentElections(string User_ID, string in_FundInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateInvestmentElections", ReplyAction = "http://transamerica.com/LosAngeles/UpdateInvestmentElectionsResponse")]
        Task<string> UpdateInvestmentElectionsAsync(string User_ID, string in_FundInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePassword", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePasswordResponse")]
        string UpdatePassword(string User_ID, string oldPass, string newPass, string genPin);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePassword", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePasswordResponse")]
        Task<string> UpdatePasswordAsync(string User_ID, string oldPass, string newPass, string genPin);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePersonalProfile", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePersonalProfileResponse")]
        string UpdatePersonalProfile(string User_ID, string PersonalProfile);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePersonalProfile", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePersonalProfileResponse")]
        Task<string> UpdatePersonalProfileAsync(string User_ID, string PersonalProfile);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateVesting", ReplyAction = "http://transamerica.com/LosAngeles/UpdateVestingResponse")]
        string UpdateVesting(string User_ID, string ParticipantVestingInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateVesting", ReplyAction = "http://transamerica.com/LosAngeles/UpdateVestingResponse")]
        Task<string> UpdateVestingAsync(string User_ID, string ParticipantVestingInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetLoanSetupItems", ReplyAction = "http://transamerica.com/LosAngeles/GetLoanSetupItemsResponse")]
        string GetLoanSetupItems(string User_ID, string LoanSetupItemsXml);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetLoanSetupItems", ReplyAction = "http://transamerica.com/LosAngeles/GetLoanSetupItemsResponse")]
        Task<string> GetLoanSetupItemsAsync(string User_ID, string LoanSetupItemsXml);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetBeneficiaryInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetBeneficiaryInfoResponse")]
        string GetBeneficiaryInfo(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/GetBeneficiaryInfo", ReplyAction = "http://transamerica.com/LosAngeles/GetBeneficiaryInfoResponse")]
        Task<string> GetBeneficiaryInfoAsync(string User_ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateBeneficiaryInfo", ReplyAction = "http://transamerica.com/LosAngeles/UpdateBeneficiaryInfoResponse")]
        string UpdateBeneficiaryInfo(string User_ID, string BeneficiaryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdateBeneficiaryInfo", ReplyAction = "http://transamerica.com/LosAngeles/UpdateBeneficiaryInfoResponse")]
        Task<string> UpdateBeneficiaryInfoAsync(string User_ID, string BeneficiaryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePXInfo", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePXInfoResponse")]
        string UpdatePXInfo(string User_ID, string PXDataXml);

        [System.ServiceModel.OperationContractAttribute(Action = "http://transamerica.com/LosAngeles/UpdatePXInfo", ReplyAction = "http://transamerica.com/LosAngeles/UpdatePXInfoResponse")]
        Task<string> UpdatePXInfoAsync(string User_ID, string PXDataXml);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IDemoParticipantServiceChannel : TRS.IT.SI.BusinessFacadeLayer.Adapters.DEMOWSPPT.IDemoParticipantService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DemoParticipantServiceClient : System.ServiceModel.ClientBase<TRS.IT.SI.BusinessFacadeLayer.Adapters.DEMOWSPPT.IDemoParticipantService>, TRS.IT.SI.BusinessFacadeLayer.Adapters.DEMOWSPPT.IDemoParticipantService
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public DemoParticipantServiceClient(EndpointConfiguration endpointConfiguration) :
                base(DemoParticipantServiceClient.GetBindingForEndpoint(endpointConfiguration), DemoParticipantServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DemoParticipantServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(DemoParticipantServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DemoParticipantServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(DemoParticipantServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DemoParticipantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string GetParticipantInfo(string User_ID)
        {
            return base.Channel.GetParticipantInfo(User_ID);
        }

        public Task<string> GetParticipantInfoAsync(string User_ID)
        {
            return base.Channel.GetParticipantInfoAsync(User_ID);
        }

        public string CancelRecurringTransfer(string User_ID)
        {
            return base.Channel.CancelRecurringTransfer(User_ID);
        }

        public Task<string> CancelRecurringTransferAsync(string User_ID)
        {
            return base.Channel.CancelRecurringTransferAsync(User_ID);
        }

        public string CancelTransaction(string User_ID, string ConfirmationNumber)
        {
            return base.Channel.CancelTransaction(User_ID, ConfirmationNumber);
        }

        public Task<string> CancelTransactionAsync(string User_ID, string ConfirmationNumber)
        {
            return base.Channel.CancelTransactionAsync(User_ID, ConfirmationNumber);
        }

        public string GenerateToken(string User_ID, string TypeCode, string UrlReturn)
        {
            return base.Channel.GenerateToken(User_ID, TypeCode, UrlReturn);
        }

        public Task<string> GenerateTokenAsync(string User_ID, string TypeCode, string UrlReturn)
        {
            return base.Channel.GenerateTokenAsync(User_ID, TypeCode, UrlReturn);
        }

        public string GetAccountSummary(string User_ID, string FromDate, string ToDate, int SumType)
        {
            return base.Channel.GetAccountSummary(User_ID, FromDate, ToDate, SumType);
        }

        public Task<string> GetAccountSummaryAsync(string User_ID, string FromDate, string ToDate, int SumType)
        {
            return base.Channel.GetAccountSummaryAsync(User_ID, FromDate, ToDate, SumType);
        }

        public string GetAllLoansData(string User_ID)
        {
            return base.Channel.GetAllLoansData(User_ID);
        }

        public Task<string> GetAllLoansDataAsync(string User_ID)
        {
            return base.Channel.GetAllLoansDataAsync(User_ID);
        }

        public string GetLoanRepaymentHistory(string User_ID)
        {
            return base.Channel.GetLoanRepaymentHistory(User_ID);
        }

        public Task<string> GetLoanRepaymentHistoryAsync(string User_ID)
        {
            return base.Channel.GetLoanRepaymentHistoryAsync(User_ID);
        }

        public string GetPassword(string User_ID)
        {
            return base.Channel.GetPassword(User_ID);
        }

        public Task<string> GetPasswordAsync(string User_ID)
        {
            return base.Channel.GetPasswordAsync(User_ID);
        }

        public string GetPendingTransactionInfo(string User_ID)
        {
            return base.Channel.GetPendingTransactionInfo(User_ID);
        }

        public Task<string> GetPendingTransactionInfoAsync(string User_ID)
        {
            return base.Channel.GetPendingTransactionInfoAsync(User_ID);
        }

        public string GetPersonalProfile(string User_ID)
        {
            return base.Channel.GetPersonalProfile(User_ID);
        }

        public Task<string> GetPersonalProfileAsync(string User_ID)
        {
            return base.Channel.GetPersonalProfileAsync(User_ID);
        }

        public string GetPlanStatus(string User_ID)
        {
            return base.Channel.GetPlanStatus(User_ID);
        }

        public Task<string> GetPlanStatusAsync(string User_ID)
        {
            return base.Channel.GetPlanStatusAsync(User_ID);
        }

        public string GetProcessingHistory(string User_ID)
        {
            return base.Channel.GetProcessingHistory(User_ID);
        }

        public Task<string> GetProcessingHistoryAsync(string User_ID)
        {
            return base.Channel.GetProcessingHistoryAsync(User_ID);
        }

        public string GetTransactionHistory(string User_ID, string FromDate, string ToDate)
        {
            return base.Channel.GetTransactionHistory(User_ID, FromDate, ToDate);
        }

        public Task<string> GetTransactionHistoryAsync(string User_ID, string FromDate, string ToDate)
        {
            return base.Channel.GetTransactionHistoryAsync(User_ID, FromDate, ToDate);
        }

        public string RebalanceFunds(string User_ID, string TransferFreq, string FundInfo)
        {
            return base.Channel.RebalanceFunds(User_ID, TransferFreq, FundInfo);
        }

        public Task<string> RebalanceFundsAsync(string User_ID, string TransferFreq, string FundInfo)
        {
            return base.Channel.RebalanceFundsAsync(User_ID, TransferFreq, FundInfo);
        }

        public string RequestLoan(string User_ID, string LoanInfo)
        {
            return base.Channel.RequestLoan(User_ID, LoanInfo);
        }

        public Task<string> RequestLoanAsync(string User_ID, string LoanInfo)
        {
            return base.Channel.RequestLoanAsync(User_ID, LoanInfo);
        }

        public string RequestPinLetter(string User_ID)
        {
            return base.Channel.RequestPinLetter(User_ID);
        }

        public Task<string> RequestPinLetterAsync(string User_ID)
        {
            return base.Channel.RequestPinLetterAsync(User_ID);
        }

        public string StatementRequest(string User_ID, string FromDate, string ToDate, string in_OM, string RptType)
        {
            return base.Channel.StatementRequest(User_ID, FromDate, ToDate, in_OM, RptType);
        }

        public Task<string> StatementRequestAsync(string User_ID, string FromDate, string ToDate, string in_OM, string RptType)
        {
            return base.Channel.StatementRequestAsync(User_ID, FromDate, ToDate, in_OM, RptType);
        }

        public string TransferFunds(string User_ID, string FundTransfer)
        {
            return base.Channel.TransferFunds(User_ID, FundTransfer);
        }

        public Task<string> TransferFundsAsync(string User_ID, string FundTransfer)
        {
            return base.Channel.TransferFundsAsync(User_ID, FundTransfer);
        }

        public string UpdateCatchupContributions(string User_ID, string CatchupInfo)
        {
            return base.Channel.UpdateCatchupContributions(User_ID, CatchupInfo);
        }

        public Task<string> UpdateCatchupContributionsAsync(string User_ID, string CatchupInfo)
        {
            return base.Channel.UpdateCatchupContributionsAsync(User_ID, CatchupInfo);
        }

        public string UpdateDeferralContributions(string User_ID, string DeferralInfo)
        {
            return base.Channel.UpdateDeferralContributions(User_ID, DeferralInfo);
        }

        public Task<string> UpdateDeferralContributionsAsync(string User_ID, string DeferralInfo)
        {
            return base.Channel.UpdateDeferralContributionsAsync(User_ID, DeferralInfo);
        }

        public string UpdateInvestmentElections(string User_ID, string in_FundInfo)
        {
            return base.Channel.UpdateInvestmentElections(User_ID, in_FundInfo);
        }

        public Task<string> UpdateInvestmentElectionsAsync(string User_ID, string in_FundInfo)
        {
            return base.Channel.UpdateInvestmentElectionsAsync(User_ID, in_FundInfo);
        }

        public string UpdatePassword(string User_ID, string oldPass, string newPass, string genPin)
        {
            return base.Channel.UpdatePassword(User_ID, oldPass, newPass, genPin);
        }

        public Task<string> UpdatePasswordAsync(string User_ID, string oldPass, string newPass, string genPin)
        {
            return base.Channel.UpdatePasswordAsync(User_ID, oldPass, newPass, genPin);
        }

        public string UpdatePersonalProfile(string User_ID, string PersonalProfile)
        {
            return base.Channel.UpdatePersonalProfile(User_ID, PersonalProfile);
        }

        public Task<string> UpdatePersonalProfileAsync(string User_ID, string PersonalProfile)
        {
            return base.Channel.UpdatePersonalProfileAsync(User_ID, PersonalProfile);
        }

        public string UpdateVesting(string User_ID, string ParticipantVestingInfo)
        {
            return base.Channel.UpdateVesting(User_ID, ParticipantVestingInfo);
        }

        public Task<string> UpdateVestingAsync(string User_ID, string ParticipantVestingInfo)
        {
            return base.Channel.UpdateVestingAsync(User_ID, ParticipantVestingInfo);
        }

        public string GetLoanSetupItems(string User_ID, string LoanSetupItemsXml)
        {
            return base.Channel.GetLoanSetupItems(User_ID, LoanSetupItemsXml);
        }

        public Task<string> GetLoanSetupItemsAsync(string User_ID, string LoanSetupItemsXml)
        {
            return base.Channel.GetLoanSetupItemsAsync(User_ID, LoanSetupItemsXml);
        }

        public string GetBeneficiaryInfo(string User_ID)
        {
            return base.Channel.GetBeneficiaryInfo(User_ID);
        }

        public Task<string> GetBeneficiaryInfoAsync(string User_ID)
        {
            return base.Channel.GetBeneficiaryInfoAsync(User_ID);
        }

        public string UpdateBeneficiaryInfo(string User_ID, string BeneficiaryInfo)
        {
            return base.Channel.UpdateBeneficiaryInfo(User_ID, BeneficiaryInfo);
        }

        public Task<string> UpdateBeneficiaryInfoAsync(string User_ID, string BeneficiaryInfo)
        {
            return base.Channel.UpdateBeneficiaryInfoAsync(User_ID, BeneficiaryInfo);
        }

        public string UpdatePXInfo(string User_ID, string PXDataXml)
        {
            return base.Channel.UpdatePXInfo(User_ID, PXDataXml);
        }

        public Task<string> UpdatePXInfoAsync(string User_ID, string PXDataXml)
        {
            return base.Channel.UpdatePXInfoAsync(User_ID, PXDataXml);
        }

        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DemoParticipantServiceSoap))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;

                // If the service requires HTTPS, uncomment the following line:
                // result.Security.Mode = BasicHttpSecurityMode.Transport;

                return result;
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name '{0}'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DemoParticipantServiceSoap))
            {
                // Read URL from configuration or use default
                string urlSetting = null; // TrsAppSettings.AppSettings.GetValue("DemoParticipantWebServiceURL");
                string url = !string.IsNullOrEmpty(urlSetting)
                    ? urlSetting
                    : "http://demo.ta-retirement.com/TRSServices/DemoParticipant.asmx";

                return new System.ServiceModel.EndpointAddress(url);
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name '{0}'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {
            DemoParticipantServiceSoap,
        }
    }
}