//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsNotification
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TRSWebServicesDev/MessageService/", ConfigurationName="TRS.IT.SI.Services.wsNotification.MessageServiceSoap")]
    public interface MessageServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/ValidateMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsNotification.KeyValueData ValidateMessage(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/ValidateMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.KeyValueData> ValidateMessageAsync(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsNotification.TWS_Response SendMessage(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.TWS_Response> SendMessageAsync(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/GetMessageVariables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsNotification.KeyValueData GetMessageVariables(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/GetMessageVariables", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.KeyValueData> GetMessageVariablesAsync(TRS.IT.SI.Services.wsNotification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRS.IT.SI.Services.wsNotification.MessageInfo GetMessage(TRS.IT.SI.Services.wsNotification.MessageQuery messageQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TRSWebServicesDev/MessageService/GetMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.MessageInfo> GetMessageAsync(TRS.IT.SI.Services.wsNotification.MessageQuery messageQuery);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class Message
    {
        
        private MessageProperties propertiesField;
        
        private MessageKeys keysField;
        
        private MessageOptions optionsField;
        
        private KeyValue[] dataField;
        
        private MessageAttachment[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageProperties Properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessageKeys Keys
        {
            get
            {
                return this.keysField;
            }
            set
            {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MessageOptions Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public KeyValue[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public MessageAttachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageProperties
    {
        
        private int messageIDField;
        
        private E_MessageType typeField;
        
        private E_MessagePriority priorityField;
        
        private string fromField;
        
        private string fromDisplayNameField;
        
        private string toField;
        
        private string ccField;
        
        private string bccField;
        
        private string subjectField;
        
        private string bodyHtmlField;
        
        private string bodyTextField;
        
        private string supportEmailAddressField;
        
        private string customDataField;
        
        private string sourceNameField;
        
        private E_MessageStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public E_MessageType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public E_MessagePriority Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FromDisplayName
        {
            get
            {
                return this.fromDisplayNameField;
            }
            set
            {
                this.fromDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Bcc
        {
            get
            {
                return this.bccField;
            }
            set
            {
                this.bccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BodyHtml
        {
            get
            {
                return this.bodyHtmlField;
            }
            set
            {
                this.bodyHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BodyText
        {
            get
            {
                return this.bodyTextField;
            }
            set
            {
                this.bodyTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SupportEmailAddress
        {
            get
            {
                return this.supportEmailAddressField;
            }
            set
            {
                this.supportEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public E_MessageStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        MessageCenter,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessagePriority
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageStatus
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        HoldForApproval,
        
        /// <remarks/>
        ReadyToSend,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        ReadyToImage,
        
        /// <remarks/>
        Imaged,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageQuery
    {
        
        private E_MessageQueryName queryNameField;
        
        private E_MessageQueryType queryTypeField;
        
        private string contractIDField;
        
        private string subIDField;
        
        private string ssnField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private string sourceNameField;
        
        private int[] messageIDsField;
        
        private string[] customDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public E_MessageQueryName QueryName
        {
            get
            {
                return this.queryNameField;
            }
            set
            {
                this.queryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public E_MessageQueryType QueryType
        {
            get
            {
                return this.queryTypeField;
            }
            set
            {
                this.queryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ssn
        {
            get
            {
                return this.ssnField;
            }
            set
            {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public int[] MessageIDs
        {
            get
            {
                return this.messageIDsField;
            }
            set
            {
                this.messageIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public string[] CustomData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageQueryName
    {
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        WebNotification,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageQueryType
    {
        
        /// <remarks/>
        ReturnLatest,
        
        /// <remarks/>
        ReturnAll,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageDetail
    {
        
        private int messageIDField;
        
        private E_MessageType typeField;
        
        private E_MessagePriority priorityField;
        
        private E_MessageStatus statusCodeField;
        
        private System.DateTime statusTimeField;
        
        private string fromField;
        
        private string fromDisplayNameField;
        
        private string toField;
        
        private string ccField;
        
        private string bccField;
        
        private string subjectField;
        
        private string bodyHtmlField;
        
        private string bodyTextField;
        
        private string supportEmailAddressField;
        
        private string customDataField;
        
        private string sourceNameField;
        
        private string contractIDField;
        
        private string subIDField;
        
        private string ssnField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private E_ImageOption imageField;
        
        private int docTypeField;
        
        private string docTypeNameField;
        
        private int batchTypeField;
        
        private string batchTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public E_MessageType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public E_MessagePriority Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public E_MessageStatus StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime StatusTime
        {
            get
            {
                return this.statusTimeField;
            }
            set
            {
                this.statusTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FromDisplayName
        {
            get
            {
                return this.fromDisplayNameField;
            }
            set
            {
                this.fromDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Bcc
        {
            get
            {
                return this.bccField;
            }
            set
            {
                this.bccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BodyHtml
        {
            get
            {
                return this.bodyHtmlField;
            }
            set
            {
                this.bodyHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BodyText
        {
            get
            {
                return this.bodyTextField;
            }
            set
            {
                this.bodyTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SupportEmailAddress
        {
            get
            {
                return this.supportEmailAddressField;
            }
            set
            {
                this.supportEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CustomData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Ssn
        {
            get
            {
                return this.ssnField;
            }
            set
            {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public E_ImageOption Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DocTypeName
        {
            get
            {
                return this.docTypeNameField;
            }
            set
            {
                this.docTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int BatchType
        {
            get
            {
                return this.batchTypeField;
            }
            set
            {
                this.batchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string BatchTypeName
        {
            get
            {
                return this.batchTypeNameField;
            }
            set
            {
                this.batchTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_ImageOption
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoImaging,
        
        /// <remarks/>
        ImageMessageAndAttachments,
        
        /// <remarks/>
        ImageMessageOnly,
        
        /// <remarks/>
        ImageAttachmentsOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class ErrorInfo
    {
        
        private int numberField;
        
        private string descriptionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyValueData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class TWS_Response
    {
        
        private ErrorInfo[] errorsField;
        
        private string confirmationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ErrorInfo[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConfirmationNumber
        {
            get
            {
                return this.confirmationNumberField;
            }
            set
            {
                this.confirmationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class KeyValueData : TWS_Response
    {
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public KeyValue[] KeyValues
        {
            get
            {
                return this.keyValuesField;
            }
            set
            {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class KeyValue
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageInfo : TWS_Response
    {
        
        private MessageDetail[] messageDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MessageDetail[] MessageDetails
        {
            get
            {
                return this.messageDetailsField;
            }
            set
            {
                this.messageDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageAttachment
    {
        
        private string nameField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateModifiedField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageOptions
    {
        
        private E_MessageErrorEmail errorEmailField;
        
        private E_MessageErrorReturn errorReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public E_MessageErrorEmail ErrorEmail
        {
            get
            {
                return this.errorEmailField;
            }
            set
            {
                this.errorEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public E_MessageErrorReturn ErrorReturn
        {
            get
            {
                return this.errorReturnField;
            }
            set
            {
                this.errorReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageErrorEmail
    {
        
        /// <remarks/>
        NoEmail,
        
        /// <remarks/>
        SendEmail_FatalErrorsOnly,
        
        /// <remarks/>
        SendEmail_AllErrors,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public enum E_MessageErrorReturn
    {
        
        /// <remarks/>
        Return_FatalErrorsOnly,
        
        /// <remarks/>
        Return_AllErrors,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRSWebServicesDev/MessageService/")]
    public partial class MessageKeys
    {
        
        private string contractIDField;
        
        private string subIDField;
        
        private string ssnField;
        
        private string allianceIDField;
        
        private string stateField;
        
        private E_ImageOption imageField;
        
        private int docTypeField;
        
        private int batchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractID
        {
            get
            {
                return this.contractIDField;
            }
            set
            {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubID
        {
            get
            {
                return this.subIDField;
            }
            set
            {
                this.subIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ssn
        {
            get
            {
                return this.ssnField;
            }
            set
            {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AllianceID
        {
            get
            {
                return this.allianceIDField;
            }
            set
            {
                this.allianceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public E_ImageOption Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int BatchType
        {
            get
            {
                return this.batchTypeField;
            }
            set
            {
                this.batchTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface MessageServiceSoapChannel : TRS.IT.SI.Services.wsNotification.MessageServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsNotification.MessageServiceSoap>, TRS.IT.SI.Services.wsNotification.MessageServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MessageServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MessageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.wsNotification.KeyValueData ValidateMessage(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.ValidateMessage(message);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.KeyValueData> ValidateMessageAsync(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.ValidateMessageAsync(message);
        }
        
        public TRS.IT.SI.Services.wsNotification.TWS_Response SendMessage(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.TWS_Response> SendMessageAsync(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.SendMessageAsync(message);
        }
        
        public TRS.IT.SI.Services.wsNotification.KeyValueData GetMessageVariables(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.GetMessageVariables(message);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.KeyValueData> GetMessageVariablesAsync(TRS.IT.SI.Services.wsNotification.Message message)
        {
            return base.Channel.GetMessageVariablesAsync(message);
        }
        
        public TRS.IT.SI.Services.wsNotification.MessageInfo GetMessage(TRS.IT.SI.Services.wsNotification.MessageQuery messageQuery)
        {
            return base.Channel.GetMessage(messageQuery);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsNotification.MessageInfo> GetMessageAsync(TRS.IT.SI.Services.wsNotification.MessageQuery messageQuery)
        {
            return base.Channel.GetMessageAsync(messageQuery);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://message-service-tst.us.aegon.com/MessageService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MessageServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://message-service-tst.us.aegon.com/MessageService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MessageServiceSoap,
            
            MessageServiceSoap12,
        }
    }
}
