//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.IT.SI.Services.wsGeneral
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transamerica.com/LosAngeles/", ConfigurationName="TRS.IT.SI.Services.wsGeneral.GeneralSoap")]
    public interface GeneralSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsGeneral.CodesInfo[] GetCodes(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.CodesInfo[]> GetCodesAsync(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetCodeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsGeneral.CodesInfo GetCodeValue(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetCodeValue", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.CodesInfo> GetCodeValueAsync(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetLastBusinessDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        string GetLastBusinessDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetLastBusinessDay", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLastBusinessDayAsync();
        
        // CODEGEN: Parameter 'GetFileBytesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFileBytes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse GetFileBytes(TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFileBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse> GetFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest request);
        
        // CODEGEN: Parameter 'GetFtpFileBytesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFtpFileBytes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse GetFtpFileBytes(TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFtpFileBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse> GetFtpFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest request);
        
        // CODEGEN: Parameter 'GetSecureFileBytesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetSecureFileBytes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse GetSecureFileBytes(TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetSecureFileBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse> GetSecureFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/CheckIfFtpFileExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        bool CheckIfFtpFileExists(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/CheckIfFtpFileExists", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckIfFtpFileExistsAsync(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFtpFileNameList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWS_Response))]
        string[] GetFtpFileNameList(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileNameWildCardPattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transamerica.com/LosAngeles/GetFtpFileNameList", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetFtpFileNameListAsync(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileNameWildCardPattern);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transamerica.com/LosAngeles/")]
    public enum E_Codes
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9999")]
        Item9999,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99999")]
        Item99999,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class CodesInfo : TWS_Response
    {
        
        private E_Codes1 codeIDField;
        
        private string codeTextField;
        
        private string codeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public E_Codes1 CodeID
        {
            get
            {
                return this.codeIDField;
            }
            set
            {
                this.codeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodeText
        {
            get
            {
                return this.codeTextField;
            }
            set
            {
                this.codeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodeValue
        {
            get
            {
                return this.codeValueField;
            }
            set
            {
                this.codeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="E_Codes", Namespace="http://TRS.SOAModel/")]
    public enum E_Codes1
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9999")]
        Item9999,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99999")]
        Item99999,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodesInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class TWS_Response
    {
        
        private ErrorInfo[] errorsField;
        
        private string confirmationNumberField;
        
        private string[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ErrorInfo[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConfirmationNumber
        {
            get
            {
                return this.confirmationNumberField;
            }
            set
            {
                this.confirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warnings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] Warnings
        {
            get
            {
                return this.warningsField;
            }
            set
            {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class ErrorInfo
    {
        
        private int numberField;
        
        private string descriptionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TRS.SOAModel/")]
    public partial class FtpRequestInfo
    {
        
        private string serverNameField;
        
        private string folderPathField;
        
        private string usernameField;
        
        private string pwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServerName
        {
            get
            {
                return this.serverNameField;
            }
            set
            {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FolderPath
        {
            get
            {
                return this.folderPathField;
            }
            set
            {
                this.folderPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Pwd
        {
            get
            {
                return this.pwdField;
            }
            set
            {
                this.pwdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileBytes", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetFileBytesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        public string sFileName;
        
        public GetFileBytesRequest()
        {
        }
        
        public GetFileBytesRequest(string sFileName)
        {
            this.sFileName = sFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileBytesResponse", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetFileBytesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileBytesResult;
        
        public GetFileBytesResponse()
        {
        }
        
        public GetFileBytesResponse(byte[] GetFileBytesResult)
        {
            this.GetFileBytesResult = GetFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFtpFileBytes", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetFtpFileBytesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        public TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=1)]
        public string sFileName;
        
        public GetFtpFileBytesRequest()
        {
        }
        
        public GetFtpFileBytesRequest(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName)
        {
            this.ftpConnectInfo = ftpConnectInfo;
            this.sFileName = sFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFtpFileBytesResponse", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetFtpFileBytesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFtpFileBytesResult;
        
        public GetFtpFileBytesResponse()
        {
        }
        
        public GetFtpFileBytesResponse(byte[] GetFtpFileBytesResult)
        {
            this.GetFtpFileBytesResult = GetFtpFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecureFileBytes", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetSecureFileBytesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        public string sFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=1)]
        public string type;
        
        public GetSecureFileBytesRequest()
        {
        }
        
        public GetSecureFileBytesRequest(string sFileName, string type)
        {
            this.sFileName = sFileName;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecureFileBytesResponse", WrapperNamespace="http://transamerica.com/LosAngeles/", IsWrapped=true)]
    public partial class GetSecureFileBytesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transamerica.com/LosAngeles/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetSecureFileBytesResult;
        
        public GetSecureFileBytesResponse()
        {
        }
        
        public GetSecureFileBytesResponse(byte[] GetSecureFileBytesResult)
        {
            this.GetSecureFileBytesResult = GetSecureFileBytesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface GeneralSoapChannel : TRS.IT.SI.Services.wsGeneral.GeneralSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GeneralSoapClient : System.ServiceModel.ClientBase<TRS.IT.SI.Services.wsGeneral.GeneralSoap>, TRS.IT.SI.Services.wsGeneral.GeneralSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GeneralSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GeneralSoapClient.GetBindingForEndpoint(endpointConfiguration), GeneralSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GeneralSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GeneralSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TRS.IT.SI.Services.wsGeneral.CodesInfo[] GetCodes(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID)
        {
            return base.Channel.GetCodes(sCodeID);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.CodesInfo[]> GetCodesAsync(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID)
        {
            return base.Channel.GetCodesAsync(sCodeID);
        }
        
        public TRS.IT.SI.Services.wsGeneral.CodesInfo GetCodeValue(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID, string sCode)
        {
            return base.Channel.GetCodeValue(sCodeID, sCode);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.CodesInfo> GetCodeValueAsync(TRS.IT.SI.Services.wsGeneral.E_Codes sCodeID, string sCode)
        {
            return base.Channel.GetCodeValueAsync(sCodeID, sCode);
        }
        
        public string GetLastBusinessDay()
        {
            return base.Channel.GetLastBusinessDay();
        }
        
        public System.Threading.Tasks.Task<string> GetLastBusinessDayAsync()
        {
            return base.Channel.GetLastBusinessDayAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetFileBytes(TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest request)
        {
            return base.Channel.GetFileBytes(request);
        }
        
        public byte[] GetFileBytes(string sFileName)
        {
            TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest();
            inValue.sFileName = sFileName;
            TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse retVal = ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetFileBytes(inValue);
            return retVal.GetFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse> TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest request)
        {
            return base.Channel.GetFileBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFileBytesResponse> GetFileBytesAsync(string sFileName)
        {
            TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetFileBytesRequest();
            inValue.sFileName = sFileName;
            return ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetFileBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetFtpFileBytes(TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest request)
        {
            return base.Channel.GetFtpFileBytes(request);
        }
        
        public byte[] GetFtpFileBytes(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName)
        {
            TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest();
            inValue.ftpConnectInfo = ftpConnectInfo;
            inValue.sFileName = sFileName;
            TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse retVal = ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetFtpFileBytes(inValue);
            return retVal.GetFtpFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse> TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetFtpFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest request)
        {
            return base.Channel.GetFtpFileBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesResponse> GetFtpFileBytesAsync(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName)
        {
            TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetFtpFileBytesRequest();
            inValue.ftpConnectInfo = ftpConnectInfo;
            inValue.sFileName = sFileName;
            return ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetFtpFileBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetSecureFileBytes(TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest request)
        {
            return base.Channel.GetSecureFileBytes(request);
        }
        
        public byte[] GetSecureFileBytes(string sFileName, string type)
        {
            TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest();
            inValue.sFileName = sFileName;
            inValue.type = type;
            TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse retVal = ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetSecureFileBytes(inValue);
            return retVal.GetSecureFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse> TRS.IT.SI.Services.wsGeneral.GeneralSoap.GetSecureFileBytesAsync(TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest request)
        {
            return base.Channel.GetSecureFileBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesResponse> GetSecureFileBytesAsync(string sFileName, string type)
        {
            TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest inValue = new TRS.IT.SI.Services.wsGeneral.GetSecureFileBytesRequest();
            inValue.sFileName = sFileName;
            inValue.type = type;
            return ((TRS.IT.SI.Services.wsGeneral.GeneralSoap)(this)).GetSecureFileBytesAsync(inValue);
        }
        
        public bool CheckIfFtpFileExists(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName)
        {
            return base.Channel.CheckIfFtpFileExists(ftpConnectInfo, sFileName);
        }
        
        public System.Threading.Tasks.Task<bool> CheckIfFtpFileExistsAsync(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileName)
        {
            return base.Channel.CheckIfFtpFileExistsAsync(ftpConnectInfo, sFileName);
        }
        
        public string[] GetFtpFileNameList(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileNameWildCardPattern)
        {
            return base.Channel.GetFtpFileNameList(ftpConnectInfo, sFileNameWildCardPattern);
        }
        
        public System.Threading.Tasks.Task<string[]> GetFtpFileNameListAsync(TRS.IT.SI.Services.wsGeneral.FtpRequestInfo ftpConnectInfo, string sFileNameWildCardPattern)
        {
            return base.Channel.GetFtpFileNameListAsync(ftpConnectInfo, sFileNameWildCardPattern);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeneralSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GeneralSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeneralSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/General.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GeneralSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://trs-services-tst.us.aegon.com:8443/General.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GeneralSoap,
            
            GeneralSoap12,
        }
    }
}
